kind:           Deployment
apiVersion:     apps/v1
metadata:
    name:       deployment-bbdd

spec:
    replicas: 1
    selector:
        matchLabels:
            {{ include "db.label.app" . }}
    template:
        metadata:
            labels:
                {{ include "db.label.app" . }}
        spec:
            containers:
                -   name:   contenedor1 
                    {{ with .Values.mariadb.image -}}
{{- /* *************************************************************************************** 
    Aqui validamos la variable pullPolicy, a la que por defecto asignamos el valor ALWAYS
******************************************************************************************** */ -}}                    
{{ $pullPolicyRellena := default "Always" .pullPolicy }}
{{- if not (regexMatch "^((IfNotPresent)|(Always)|(Never))$" $pullPolicyRellena ) }}
    {{ fail (printf "El valor suministrador para la propiedad mariadb.image.pullpolicy: '%s' no es válido. Debe debe tener como valor: Always, IfnotPresent o Never." .pullPolicy) }}
{{ end -}}

                    image:  {{ required "Debe suministrar el repo de la imagen de mariadb: mariadb.image.repo" .repo -}}
                            :{{ required "Debe suministrar el tag de la imagen de mariadb: mariadb.image.tag" .tag }}
                    imagePullPolicy: {{ $pullPolicyRellena }}
                    {{- end }}
                    resources:
                        requests: 
                            cpu:    500m
                            memory: 1Gi
                        limits:
                            cpu:    8
                            memory: 1Gi
                    env:
                        -   name:   MARIADB_ROOT_PASSWORD
                            valueFrom:  
                                secretKeyRef:    
                                    name:   {{ include "secret.name" . }}
                                    key:    contrasena-root
                        -   name:   MARIADB_DATABASE
                            valueFrom:  
                                configMapKeyRef:    
                                    name:   {{ include "configmap.name" . }}
                                    key:    nombre_bbdd
                        -   name:   MARIADB_USER
                            valueFrom:  
                                secretKeyRef:    
                                    name:   {{ include "secret.name" . }}
                                    key:    usuario     
                        -   name:   MARIADB_PASSWORD
                            valueFrom:  
                                secretKeyRef:    
                                    name:   {{ include "secret.name" . }}
                                    key:    contrasena-usuario
                    volumeMounts:
                        - name:         {{ include "db.volume.name" . }}
                          mountPath:    /var/lib/mysql
            volumes:
                - name: {{ include "db.volume.name" . }}
                  persistentVolumeClaim: 
                    claimName: {{ include "db.pvc.name" . }}
