kind:           Deployment
apiVersion:     apps/v1
metadata:
    name:       deployment-bbdd

spec:
    replicas: 1
    selector:
        matchLabels:
            {{ include "db.label.app" . }}
    template:
        metadata:
            labels:
                {{ include "db.label.app" . }}
        spec:
            containers:
                -   name:   contenedor1 
                    {{- include "image" .Values.mariadb.image | nindent 20 -}}
                    {{- include "resources" (merge .Values.mariadb.resources (dict "field" "mariadb" )) | nindent 20 }}
                    env:
                        -   name:   MARIADB_ROOT_PASSWORD
                            valueFrom:  
                                secretKeyRef:    
                                    name:   {{ include "secret.name" . }}
                                    key:    contrasena-root
                        -   name:   MARIADB_DATABASE
                            valueFrom:  
                                configMapKeyRef:    
                                    name:   {{ include "configmap.name" . }}
                                    key:    nombre_bbdd
                        -   name:   MARIADB_USER
                            valueFrom:  
                                secretKeyRef:    
                                    name:   {{ include "secret.name" . }}
                                    key:    usuario     
                        -   name:   MARIADB_PASSWORD
                            valueFrom:  
                                secretKeyRef:    
                                    name:   {{ include "secret.name" . }}
                                    key:    contrasena-usuario
# Llevar a una plantilla... y contar en qué campo habría que meter el valor correspondiente a las variables prohibidas
{{/*- $variablesNoPermitidas := list "MARIADB_ROOT_PASSWORD" "MARIADB_DATABASE" "MARIADB_USER" "MARIADB_PASSWORD" */-}}
{{- $variablesNoPermitidas := dict "MARIADB_ROOT_PASSWORD" "mariadb.config.rootPassword" -}}
{{ $_ := set $variablesNoPermitidas "MARIADB_DATABASE" "mariadb.config.dbName" }}
{{ $_ := set $variablesNoPermitidas "MARIADB_USER" "mariadb.config.user" }}
{{ $_ := set $variablesNoPermitidas "MARIADB_PASSWORD" "mariadb.config.password" }}

{{- range $clave, $valor := .Values.mariadb.config.extraEnvVars -}}
    {{- if hasKey $clave $variablesNoPermitidas -}}
     {{- fail (printf "No puede definir la variable %s como extraEnvVars. En su lugar utilice: %s" $clave (get $variablesNoPermitidas $clave ) ) -}}
    {{- end }}
                        -   name: {{ $clave }}
                            value: {{ $valor | quote}}
{{- end }}                        
                    volumeMounts:
                        - name:         {{ include "db.volume.name" . }}
                          mountPath:    /var/lib/mysql
            volumes:
                - name: {{ include "db.volume.name" . }}
                  persistentVolumeClaim: 
                    claimName: {{ include "db.pvc.name" . }}
