kind:           Deployment
apiVersion:     apps/v1
metadata:
    name:       deployment-bbdd

spec:
    replicas: 1
    selector:
        matchLabels:
            {{ include "db.label.app" . }}
    template:
        metadata:
            labels:
                {{ include "db.label.app" . }}
        spec:
            containers:
                -   name:   contenedor1 
                    {{- include "image" .Values.mariadb.image | nindent 20 -}}
                    {{- include "resources" (merge .Values.mariadb.resources (dict "field" "mariadb" )) | nindent 20 }}
                    env:
                        -   name:   MARIADB_ROOT_PASSWORD
                            valueFrom:  
                                secretKeyRef:    
                                    name:   {{ include "secret.name" . }}
                                    key:    contrasena-root
                        -   name:   MARIADB_DATABASE
                            valueFrom:  
                                configMapKeyRef:    
                                    name:   {{ include "configmap.name" . }}
                                    key:    nombre_bbdd
                        -   name:   MARIADB_USER
                            valueFrom:  
                                secretKeyRef:    
                                    name:   {{ include "secret.name" . }}
                                    key:    usuario     
                        -   name:   MARIADB_PASSWORD
                            valueFrom:  
                                secretKeyRef:    
                                    name:   {{ include "secret.name" . }}
                                    key:    contrasena-usuario
# Necesitamos montar un bucle sobre el que ir iterando
{{- range $clave, $valor := .Values.mariadb.config.extraEnvVars }}
                        -   name: {{ $clave }}
                            value: {{ $valor }}
{{ end -}}                        
                        
                    volumeMounts:
                        - name:         {{ include "db.volume.name" . }}
                          mountPath:    /var/lib/mysql
            volumes:
                - name: {{ include "db.volume.name" . }}
                  persistentVolumeClaim: 
                    claimName: {{ include "db.pvc.name" . }}
