---
{{ if (and (.Values.mariadb.persistence.enabled) (not .Values.mariadb.persistence.existingPvcName)) }}

{{ if not ( regexMatch "^[1-9][0-9]*[GMTK]i$" 
    ( required "Debe especificar el tamño del volumen de la BBDD: 'mariadb.persistence.capacity'" .Values.mariadb.persistence.capacity )
) }}
    {{ fail (printf "El valor suministrador para la capacidad: '%s' no es válido. Ejemplos de valores válidos: 1Gi, 16Ti, 9Mi" .Values.mariadb.persistence.capacity) }}
{{ end }}

kind:           PersistentVolumeClaim
apiVersion:     v1
metadata:
    name:       peticion-volumen-mariadb
spec:
    resources:
        requests:
            storage: {{ .Values.mariadb.persistence.capacity }}
    {{- if .Values.mariadb.persistence.storageClass }}
    storageClassName: {{ .Values.mariadb.persistence.storageClass -}}
    {{ end }}
    accessModes:
        - ReadWriteOncePod
{{ end }}