---
{{ with .Values.mariadb.persistence }}

{{ if (and (.enabled) (not .existingPvcName)) }}

{{ include "check.bytes" ( dict "required" true "field" "mariadb.persistence.capacity" "value" .capacity ) }}

kind:           PersistentVolumeClaim
apiVersion:     v1
metadata:
    name:       {{.Release.Name}}-{{ include "db.pvc.name" $ }}
spec:
    resources:
        requests:
            storage: {{ .capacity }}
    {{- if .storageClass }}
    storageClassName: {{ $.Values.mariadb.persistence.storageClass -}}
    {{ end }}
    accessModes:
        - ReadWriteOncePod
        
{{ end }}
{{ end }}