---
{{ with .Values.mariadb.persistence }}
{{ if (and (.enabled) (not .existingPvcName)) }}

{{ if not ( regexMatch "^[1-9][0-9]*[GMTK]i$" 
    ( required "Debe especificar el tamño del volumen de la BBDD: 'mariadb.persistence.capacity'" .capacity )
) }}
    {{ fail (printf "El valor suministrador para la capacidad: '%s' no es válido. Ejemplos de valores válidos: 1Gi, 16Ti, 9Mi" .capacity) }}
{{ end }}

kind:           PersistentVolumeClaim
apiVersion:     v1
metadata:
    name:       peticion-volumen-mariadb
spec:
    resources:
        requests:
            storage: {{ .capacity }}
    {{- if .storageClass }}
    storageClassName: {{ $.Values.mariadb.persistence.storageClass -}}
    {{ end }}
    accessModes:
        - ReadWriteOncePod
{{ end }}
{{ end }}