kind:           PersistentVolume
apiVersion:     v1
metadata:
    name:       volumen-mariadb
spec:
    capacity: 
        storage: 1Gi
    storageClassName: rapidito-redundante # Tipo de volumen
    accessModes: # Esto va condicionado, no solo por lo que yo necesite... si no por lo que el volumen real permita
        - ReadWriteOnce # Quiero un volumen para mi, que una vez montado en un host, no se entregue a otro host
                        # Aunque dentro de ese host, lo podría usar en multiples pods
        - ReadWriteMany # Quiero un volumen que pueda ser usado por múltiples pods, en múltiples hosts
        - ReadOnlyMany  # Quiero un volumen que pueda ser usado EN SOLO LECTURA por múltiples pods, en múltiples hosts
        - ReadWriteOncePod # Quiero un volumen para mi, que una vez montado en un host, no se entregue a otro host
                           # Y dentro de ese host, solo pueda usarse en un pods
    hostPath:
        path: /home/ubuntu/environment/datos/mariadb # En el host
        type: DirectoryOrCreate
---
kind:           PersistentVolumeClaim
apiVersion:     v1
metadata:
    name:       peticion-volumen-mariadb
spec:
    resources:
        requests:
            storage: 1Gi
    storageClassName: rapidito-redundante # Tipo de volumen
    accessModes: # Esto va condicionado, no solo por lo que yo necesite... si no por lo que el volumen real permita
        #- ReadWriteOnce # Quiero un volumen para mi, que una vez montado en un host, no se entregue a otro host
                        # Aunque dentro de ese host, lo podría usar en multiples pods
        #- ReadWriteMany # Quiero un volumen que pueda ser usado por múltiples pods, en múltiples hosts
        #- ReadOnlyMany  # Quiero un volumen que pueda ser usado EN SOLO LECTURA por múltiples pods, en múltiples hosts
        - ReadWriteOncePod # Quiero un volumen para mi, que una vez montado en un host, no se entregue a otro host
                           # Y dentro de ese host, solo pueda usarse en un pods
---
kind:           ConfigMap
apiVersion:     v1
metadata:
    name:       configuracion-mariadb

data:
    nombre_bbdd:    curso
---
kind:           ConfigMap
apiVersion:     v1
metadata:
    name:       fichero-configuracion-mariadb

data:
    mariadb.conf: |
        contenido del fichero
        con todas sus lineas
        y más 
---
kind:           Secret
apiVersion:     v1
metadata:
    name:       configuracion-mariadb-secreta

data:
    contraseña-root:        cGFzc3dvcmQ= # Ponemos los valores en base64
    contraseña-usuario:     cGFzc3dvcmQ= # La única diferencia con respecto a los 
                                         # secret es que se guardan encriptados dentro de Kubernetes
    usuario:                dXN1YXJpbw==
---
kind:           Service
apiVersion:     v1
metadata:
    name:       servicio-bbdd

spec:
    type:       ClusterIP
    ports:
        - port: 3306
          targetPort: 3306
    selector:
        app:    mariadb
---
kind:           Deployment
apiVersion:     apps/v1
metadata:
    name:       deployment-bbdd

spec:
    replicas: 1
    selector:
        matchLabels:
            app:    mariadb
    template:
        metadata:
            labels:
                app:    mariadb
        spec:
            containers:
                -   name:   contenedor1 
                    image:  mariadb:latest 
                    imagePullPolicy: IfNotPresent
                    # Cuanta CPU y RAM le dejo?
                    # ESTO ES UNA MEDIDA DE GRACIA (un control de seguridad)
                    # El sitio donde definir esto (especialmente lo relativo a Memoria RAM) es el proceso que corro
                    # Eso lo quiero definir en la propia BBDD.. Que tendrá su fichero de configuración
                    resources:
                        requests: # Esto se usa por el planificador en primera instancia. Para determinar a qué máquina se asigna el pod (scheduler)
                                  # Esto realmente limita el uso de la memoria y cpu? Podría en según que caso
                            cpu:    500m
                            memory: 1Gi
                        limits:   # Limite real de uso de recursos en caso de que haya disponible
                            cpu:    8   # No significa que al proceso de la BBDD le asigno 1 core de la máquina
                                        # Le dejo que use el equivalente a 1 core por unidad de tiempo.
                            memory: 1Gi # El mismo que arriba.. Si tomo más y luego otro la necesita, me matan.
                    env:
                        -   name:   MARIADB_ROOT_PASSWORD
                            valueFrom:  
                                secretKeyRef:    
                                    name:   configuracion-mariadb-secret
                                    key:    contraseña-root
                        -   name:   MARIADB_DATABASE # Configmap
                            valueFrom:  
                                configMapKeyRef:    
                                    name:   configuracion-mariadb
                                    key:    nombre_bbdd
                        -   name:   MARIADB_USER
                            valueFrom:  
                                secretKeyRef:    
                                    name:   configuracion-mariadb-secret
                                    key:    usuario     
                        -   name:   MARIADB_PASSWORD
                            valueFrom:  
                                secretKeyRef:    
                                    name:   configuracion-mariadb-secret
                                    key:    contraseña-usuario
                    volumeMounts:
                        - name:         datos-bbdd
                          mountPath:   /var/lib/mysql
                        - name:         fichero-del-mariadb
                          mountPath:   /etc/mariadb
            volumes:
                - name: fichero-del-mariadb
                  configMap: fichero-configuracion-mariadb
                - name: datos-bbdd
                  # Yo, como persona que necesita desplegar una app, diré:
                  # Quiero un volumen, rapidito-redundante de 10 Gbs
                  persistentVolumeClaim: peticion-volumen-mariadb
---
# WORDPRESS
kind:           PersistentVolume
apiVersion:     v1
metadata:
    name:       volumen-wordpress
spec:
    capacity: 
        storage: 1Gi
    storageClassName: rapidito-redundante # Tipo de volumen
    accessModes: # Esto va condicionado, no solo por lo que yo necesite... si no por lo que el volumen real permita
        - ReadWriteOnce # Quiero un volumen para mi, que una vez montado en un host, no se entregue a otro host
                        # Aunque dentro de ese host, lo podría usar en multiples pods
        - ReadWriteMany # Quiero un volumen que pueda ser usado por múltiples pods, en múltiples hosts
        - ReadOnlyMany  # Quiero un volumen que pueda ser usado EN SOLO LECTURA por múltiples pods, en múltiples hosts
        - ReadWriteOncePod # Quiero un volumen para mi, que una vez montado en un host, no se entregue a otro host
                           # Y dentro de ese host, solo pueda usarse en un pods
    hostPath:
        path: /home/ubuntu/environment/datos/wordpress # En el host
        type: DirectoryOrCreate
---
kind:           PersistentVolumeClaim
apiVersion:     v1
metadata:
    name:       peticion-volumen-wordpress
spec:
    resources:
        requests:
            storage: 1Gi
    storageClassName: rapidito-redundante # Tipo de volumen
    accessModes: # Esto va condicionado, no solo por lo que yo necesite... si no por lo que el volumen real permita
        #- ReadWriteOnce # Quiero un volumen para mi, que una vez montado en un host, no se entregue a otro host
                        # Aunque dentro de ese host, lo podría usar en multiples pods
        #- ReadWriteMany # Quiero un volumen que pueda ser usado por múltiples pods, en múltiples hosts
        #- ReadOnlyMany  # Quiero un volumen que pueda ser usado EN SOLO LECTURA por múltiples pods, en múltiples hosts
        - ReadWriteOncePod # Quiero un volumen para mi, que una vez montado en un host, no se entregue a otro host
                           # Y dentro de ese host, solo pueda usarse en un pods
---
kind:           Service
apiVersion:     v1
metadata:
    name:       servicio-wordpress

spec:
    type:       ClusterIP # NodePort # LoadBalancer #+Ingress
    ports:
        - port: 80
          targetPort: 80
    selector:
        app:    wordpress
---
kind:           Deployment
apiVersion:     apps/v1
metadata:
    name:       deployment-wordpress

spec:
    replicas: 2
    selector:
        matchLabels:
            app:    wordpress
    template:
        metadata:
            labels:
                app:    wordpress
        spec:
            affinity:
                podAntiAffinity: 
                    preferredDuringSchedulingIgnoredDuringExecution:
                     -  weight: 100
                        labelSelector:
                          matchExpressions:
                          - key: app
                            operator: In
                            values:
                            - wordpress
                        topologyKey: "kubernetes.io/hostname"   # A nivel de host                     
                
            containers:
                -   name:   contenedor1 
                    image:  wordpress:latest 
                    imagePullPolicy: IfNotPresent
                    # Cuanta CPU y RAM le dejo?
                    # ESTO ES UNA MEDIDA DE GRACIA (un control de seguridad)
                    # El sitio donde definir esto (especialmente lo relativo a Memoria RAM) es el proceso que corro
                    # Eso lo quiero definir en la propia BBDD.. Que tendrá su fichero de configuración
                    resources:
                        requests: # Esto se usa por el planificador en primera instancia. Para determinar a qué máquina se asigna el pod (scheduler)
                                  # Esto realmente limita el uso de la memoria y cpu? Podría en según que caso
                            cpu:    500m
                            memory: 1Gi
                        limits:   # Limite real de uso de recursos en caso de que haya disponible
                            cpu:    8   # No significa que al proceso de la BBDD le asigno 1 core de la máquina
                                        # Le dejo que use el equivalente a 1 core por unidad de tiempo.
                            memory: 1Gi # El mismo que arriba.. Si tomo más y luego otro la necesita, me matan.
                    env:
                        -   name:   WORDPRESS_DB_HOST
                            value:    servicio-bbdd:3306
                        -   name:   WORDPRESS_DB_NAME # Configmap
                            valueFrom:  
                                configMapKeyRef:    
                                    name:   configuracion-mariadb
                                    key:    nombre_bbdd
                        -   name:   WORDPRESS_DB_USER
                            valueFrom:  
                                secretKeyRef:    
                                    name:   configuracion-mariadb-secret
                                    key:    usuario     
                        -   name:   WORDPRESS_DB_PASSWORD
                            valueFrom:  
                                secretKeyRef:    
                                    name:   configuracion-mariadb-secret
                                    key:    contraseña-usuario
                    volumeMounts:
                        - name:         datos-wordpress
                          mountPath:   /var/www/html
            volumes:
                - name: datos-wordpress
                  # Yo, como persona que necesita desplegar una app, diré:
                  # Quiero un volumen, rapidito-redundante de 10 Gbs
                  persistentVolumeClaim: peticion-volumen-wordpress
---
# WP: o un ingress o modificar el servicio para que sea de tipo Nodeport o loadbalance 
# Autoescalador wp