---
{{ with .Values.wordpress.persistence }}

{{ if (and (.enabled) (not .existingPvcName)) }}

{{ include "check.bytes" ( dict "required" true "field" "wordpress.persistence.capacity" "value" .capacity ) }}

kind:           PersistentVolumeClaim
apiVersion:     v1
metadata:
    name:       peticion-volumen-wordpress
spec:
    resources:
        requests:
            storage: {{ .capacity }}
    {{- if .storageClass }}
    storageClassName: {{ .storageClass -}}
    {{ end }}
    accessModes:
        - ReadWriteOncePod
        
{{ end }}
{{ end }}