---
kind:           Service
apiVersion:     v1
metadata:
    name:       servicio-wordpress

spec:
    type:       ClusterIP
    ports:
        - port: 80
          targetPort: 80
    selector:
        app:    wordpress
