---
kind:           ConfigMap
apiVersion:     v1
metadata:
    name:       {{ include "configmap.name" . }}

data:
    nombre_bbdd:    {{ default "wp-db" .Values.mariadb.config.dbName | trim | lower | quote }}
                    # Listado de filtros disponibles: https://helm.sh/docs/chart_template_guide/function_list/
