---
{{ if not .Values.mariadb.config.existingSecretName }}
kind:           Secret
apiVersion:     v1
metadata:
    name:       {{ include "secret.name" . }}

data:
    contrasena-root:        {{ (default (randAscii 15) .Values.mariadb.config.rootPassword) | trim | b64enc | quote }}
    contrasena-usuario:     {{ if .Values.mariadb.config.password }}
                                {{- .Values.mariadb.config.password | trim | b64enc | quote -}}
                            {{ else -}}
                                {{ randAscii 15 | trim | b64enc | quote }}
                            {{- end }}
    usuario:                {{ (default "dbuser" .Values.mariadb.config.user) | trim | b64enc | quote }}
{{ end }}